<a href="https://colab.research.google.com/github/tanyasheru23/PyTorch/blob/main/00_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Have a happy learning in PyTorch!!!


In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


###Introduction to tensors

creating tensors

represent multidimensional data


In [2]:
#scalar

scalar = torch.tensor(7)
scalar
#go through documentation

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as Python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([6,8])
vector

tensor([6, 8])

In [6]:
vector.ndim
#number of sq brackets

1

In [7]:
vector.shape
#2 elements

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[2,3],[4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [9]:
print(MATRIX.ndim)
print(MATRIX.shape)
MATRIX[1]

2
torch.Size([2, 2])


tensor([4, 5])

In [10]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[2,3,4],[8,9,5]]])
TENSOR, TENSOR.ndim, TENSOR[0], TENSOR[0,1], TENSOR.shape #1 3/3 tensor,

(tensor([[[1, 2, 3],
          [2, 3, 4],
          [8, 9, 5]]]),
 3,
 tensor([[1, 2, 3],
         [2, 3, 4],
         [8, 9, 5]]),
 tensor([2, 3, 4]),
 torch.Size([1, 3, 3]))

Random Tensors

Important because, many NN learn is that they start with tensors full of random numbers and then adjust those random numbers for better represent the data

start with random numbers ⟶ look at data ⟶ update random numbers ⟶ look at data ⟶ update random numbers

In [11]:
# create a Random tensor of size (3,4)
rand_tensor = torch.rand(3,4)
#go through the doc
rand_tensor

tensor([[0.4307, 0.1452, 0.0013, 0.3303],
        [0.0059, 0.5998, 0.3069, 0.4817],
        [0.0850, 0.4709, 0.0024, 0.0709]])

In [12]:
print(rand_tensor.ndim)
print(rand_tensor.shape)

2
torch.Size([3, 4])


In [13]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
#[224, 224, 3] ([height, width, color_channels]).
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeroes and Ones

In [14]:
# create a tensor of all zeroes
zeros = torch.zeros(3,4)
# create a tensor of all ones
ones = torch.ones(3,4)

zeros, ones, ones.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Tensor like, ranges

In [15]:
one_to_ten = torch.arange(1,23,2)
some_zeros = torch.zeros_like(input=one_to_ten)

one_to_ten, some_zeros

(tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

###Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and DL
1. Tensors not right datatype
2. Tensors not right shape(while mat multiplication)
3. Tensors not on the right device

In [16]:
fl_32 = torch.tensor([3.0,6.0,9.0],dtype=None, device = None)
fl_32.dtype

torch.float32

In [17]:
fl_16 = fl_32.type(torch.float16)
fl_16

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
t = fl_16*fl_32
t.dtype

torch.float32

In [19]:
int_32 = torch.tensor([3,6,9], dtype=torch.int32)
int_32

tensor([3, 6, 9], dtype=torch.int32)

In [20]:
int_32*fl_16

tensor([ 9., 36., 81.], dtype=torch.float16)

In [21]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Shape of the Tensor: {some_tensor.shape}")
print(f"DataType of the Tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9396, 0.3059, 0.8022, 0.6806],
        [0.0162, 0.9515, 0.1149, 0.0878],
        [0.9845, 0.9417, 0.9138, 0.2429]])
Shape of the Tensor: torch.Size([3, 4])
DataType of the Tensor: torch.float32
Device tensor is on: cpu


### Manipulating Tensors(tensor operations)

Tensor operations include
* addition
* subtraction
* multiplication
* division
* matrix multiplication

In [22]:
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor*10)
# tryout inbuilt functions
torch.mul(tensor,2)

tensor([11, 12, 13])
tensor([10, 20, 30])


tensor([2, 4, 6])

In [23]:
# element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

#matrix multiplication)

print(f"Matrix multiplication equals: {torch.matmul(tensor,tensor)}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Matrix multiplication equals: 14


In [24]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 468 µs, sys: 93 µs, total: 561 µs
Wall time: 1.66 ms


In [25]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 30 µs, sys: 6 µs, total: 36 µs
Wall time: 39.1 µs


tensor(14)

### one of the most COMMON ERRORS in DL

2 main rules that performing matmul need to satisfy:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [26]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm(tensor_A,tensor_B) can't be multiplied
#torch.mm is short form of torch.matmul
print(tensor_A)
print(tensor_B,tensor_B.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) torch.Size([3, 2])


In [27]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [28]:
torch.mm(tensor_A, tensor_B.T),torch.mm(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

## Find the min, max, mean, sum, etc (tensor aggregation)

In [29]:
x = torch.arange(3,105, 10)
x, x.dtype

(tensor([  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103]), torch.int64)

In [30]:
torch.min(x), x.min()

(tensor(3), tensor(3))

In [31]:
torch.max(x), x.max()

(tensor(103), tensor(103))

In [32]:
#torch.mean inputs only datatype of float32
#hence we need to convert type of x
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(53.), tensor(53.))

In [33]:
# sum
torch.sum(x), x.sum()

(tensor(583), tensor(583))

In [34]:
# index position of min and max values in the tensor
x.argmin(), x.argmax()

(tensor(0), tensor(10))

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as th original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [35]:
# Let's create a tensor
x = torch.arange(1.0,10.0)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [37]:
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [38]:
z = x.view(1,9)
#here as z shares the same memory as x, any changes made in z will also show up in the original x
print(z)
z[:,0]=5.0
print(z)
print(x)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [39]:
#stacking the tensors
x_stacked = torch.stack((x,x,x,x),dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [40]:
torch.vstack((x,x,x,x)), torch.vstack((x,x,x,x)).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [41]:
torch.hstack((x,x,x,x)), torch.hstack((x,x,x,x)).shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([36]))

In [42]:
print(f"Previous tensor: {x_reshape}\n")
print(f"Previous shape: {x_reshape.shape}\n")

#remove extra dimensions from the x_reshaped
x_squeezed = x_reshape.squeeze()
print(f"New Tensor: {x_squeezed}\n")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [43]:
#torch.unsqueeze adds a single dim to a target at a specific dim
print(f"Previous tensor: {x_squeezed}\n")
print(f"Previous shape: {x_squeezed.shape}\n")

#add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) #add dim at dim 1
print(f"New Tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}\n\n")

x_unsqueezed = x_squeezed.unsqueeze(dim=0) #add dim at dim 0
print(f"New Tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

Previous shape: torch.Size([9])

New Tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New shape: torch.Size([9, 1])


New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [44]:
x_new = x_reshape.reshape(3,3)
print(f"Previous tensor: {x_new}\n")
print(f"Previous shape: {x_new.shape}\n")

#remove extra dimensions from the x_new
x_squeezed = x_new.squeeze()
print(f"New Tensor: {x_squeezed}\n")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Previous shape: torch.Size([3, 3])

New Tensor: tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

New shape: torch.Size([3, 3])


In [45]:
#torch.unsqueeze adds a single dim to a target at a specific dim
print(f"Previous tensor: {x_squeezed}\n")
print(f"Previous shape: {x_squeezed.shape}\n")

#add an extra dimension with unsqueeze
print("Unsqueezing in Dim 2")
x_unsqueezed = x_squeezed.unsqueeze(dim=2) #add dim at dim 2
print(f"New Tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}\n")
print("---------------------------------------\n")

print("Unsqueezing in Dim 1\n")
x_unsqueezed = x_squeezed.unsqueeze(dim=1) #add dim at dim 1
print(f"New Tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}\n")
print("---------------------------------------\n")

print("Unsqueezing in Dim 0\n")
x_unsqueezed = x_squeezed.unsqueeze(dim=0) #add dim at dim 0
print(f"New Tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}")
print("---------------------------------------")


Previous tensor: tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Previous shape: torch.Size([3, 3])

Unsqueezing in Dim 2
New Tensor: tensor([[[5.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])

New shape: torch.Size([3, 3, 1])

---------------------------------------

Unsqueezing in Dim 1

New Tensor: tensor([[[5., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])

New shape: torch.Size([3, 1, 3])

---------------------------------------

Unsqueezing in Dim 0

New Tensor: tensor([[[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

New shape: torch.Size([1, 3, 3])
---------------------------------------


Permute is commonly used with images

In [46]:
# torch.permute rearranges the dimensions of a target tensor in a specified order
x = torch.randint(2,10,(2,4,3))
print(f"The size of the tensor is: {x.shape}\n")
print(f"The tensor is: {x}\n\n")

#now rearrange the shape as you need by changing in the index of the dim
print("\n-------------New permutation 2,0,1---------------------\n")
x_permuted = x.permute(2,0,1)
print(f"The size of the permuted tensor is: {x_permuted.shape}\n")
print(f"The permuted tensor is: {x_permuted}")


The size of the tensor is: torch.Size([2, 4, 3])

The tensor is: tensor([[[7, 8, 4],
         [9, 2, 9],
         [8, 5, 9],
         [3, 3, 2]],

        [[2, 7, 5],
         [4, 8, 5],
         [5, 4, 4],
         [9, 7, 4]]])



-------------New permutation 2,0,1---------------------

The size of the permuted tensor is: torch.Size([3, 2, 4])

The permuted tensor is: tensor([[[7, 9, 8, 3],
         [2, 4, 5, 9]],

        [[8, 2, 5, 3],
         [7, 8, 4, 7]],

        [[4, 9, 9, 2],
         [5, 5, 4, 4]]])


In [47]:
# permuted and original tensors share the same memory
# try changing the value in permuted on and check the original one

x_permuted[:,:,0] = 0
print(f"The new permuted tensor is: {x_permuted}\n")
print(f"Now let's see what happened in the original tensor: {x}")

The new permuted tensor is: tensor([[[0, 9, 8, 3],
         [0, 4, 5, 9]],

        [[0, 2, 5, 3],
         [0, 8, 4, 7]],

        [[0, 9, 9, 2],
         [0, 5, 4, 4]]])

Now let's see what happened in the original tensor: tensor([[[0, 0, 0],
         [9, 2, 9],
         [8, 5, 9],
         [3, 3, 2]],

        [[0, 0, 0],
         [4, 8, 5],
         [5, 4, 4],
         [9, 7, 4]]])


In [48]:
x = torch.randint(2,10,(2,4,3))

print("\n-------------New permutation 1,2,0---------------------\n")
x_permuted = x.permute(1,2,0)
print(f"The size of the permuted tensor is: {x_permuted.shape}\n")
print(f"The permuted tensor is: {x_permuted}")


-------------New permutation 1,2,0---------------------

The size of the permuted tensor is: torch.Size([4, 3, 2])

The permuted tensor is: tensor([[[4, 5],
         [3, 6],
         [3, 7]],

        [[9, 4],
         [6, 2],
         [3, 3]],

        [[4, 3],
         [8, 4],
         [3, 2]],

        [[9, 6],
         [6, 4],
         [2, 6]]])


In [49]:
# permuted and original tensors share the same memory
# try changing the value in permuted on and check the original one

x_permuted[:,:,0] = 0
print(f"The new permuted tensor is: {x_permuted}\n")
print(f"Now let's see what happened in the original tensor: {x}")

The new permuted tensor is: tensor([[[0, 5],
         [0, 6],
         [0, 7]],

        [[0, 4],
         [0, 2],
         [0, 3]],

        [[0, 3],
         [0, 4],
         [0, 2]],

        [[0, 6],
         [0, 4],
         [0, 6]]])

Now let's see what happened in the original tensor: tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[5, 6, 7],
         [4, 2, 3],
         [3, 4, 2],
         [6, 4, 6]]])


In [50]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
x[0,0] #or x[0][0]

tensor([1, 2, 3])

In [53]:
# let's index on most inner bracket
x[0][2][1]

tensor(8)

In [54]:
# you can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [55]:
x[:,:,0]

tensor([[1, 4, 7]])

In [56]:
x[0,2,:]

tensor([7, 8, 9])

In [57]:
import torch
x = torch.arange(1,19).reshape(3,3,2)
x, x.shape

(tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16],
          [17, 18]]]),
 torch.Size([3, 3, 2]))

In [58]:
x[0]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [59]:
x[0,0] #or x[0][0]

tensor([1, 2])

In [60]:
# let's index on most inner bracket
x[0][2][1]

tensor(6)

In [61]:
# you can use ":" to select all of a target dimension
x[:,0]

tensor([[ 1,  2],
        [ 7,  8],
        [13, 14]])

In [62]:
x[:,:,0]

tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]])

In [63]:
x[0,2,:]

tensor([5, 6])

In [64]:
# Indexing (selecting data from tensors)
# similar to numpy

### PyTorch and NumPy

NumPy is a popular scientific Python numerical computing library
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [65]:
#numpys default dtype is float 64 whereas torch's tensor default dtype is float32
import numpy as np

array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [66]:
#change the value in array -> what affect will it have on tensor
array = array+1
array, tensor
#it didn't change i.e both have different memory space

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [67]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor
#default dtype of array will be that of tensor now

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

## Reproducability (trying to take random out of random)

In short how s neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again..`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

A pseudorandom number generator's number sequence is completely determined by the seed: thus, if a pseudorandom number generator is reinitialized with the same seed, it will produce the same sequence of numbers.

In [68]:
# Let's make some random but reproducilble tensors

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

#the below line of code works only for one random gen
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B==random_tensor_A)
#hence we get the same random numbers or data

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making computations easier)

In [69]:
!nvidia-smi

Sun Mar 17 10:45:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [70]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [71]:
# Set-up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [72]:
#count number of devices
torch.cuda.device_count()

1

Putting tensors on the GPU

In [73]:
import torch
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [74]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensors back to the CPU

In [75]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [76]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [77]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')